name: Branches

on:
  pull_request:
    types: [opened, reopened]
    branches: ["main"]

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A - Current branch of PR is ${{github.ref}}"
      - run: echo "A - Current branch of PR is ${{github.head_ref}}"
      - run: echo "A - Current branch of PR is ${{github.base_ref}}"
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - run: |
          jq '.branches += ["${{github.head_ref}}""]' active-branches.json > temp.json
          mv temp.json active-branches.json
      - run: cp -a ./active-branches.json ./deploy
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: deploy/

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: update-branches
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: gh-pages
  #     - name: Download deploy artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: deploy
  #     - name: Commit & Push changes
  #       uses: actions-js/push@master
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         author_name: "Github action"
  #         message: "Update active branches"
  #         branch: "gh-pages"
