name: Branches

on:
  pull_request:
    types: [opened, reopened, closed]
    branches: ["main", "develop"]

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - run: mkdir -p deploy-pr/pr
      - run: |
          if [ ${{github.event.pull_request.state}} = 'open' ]; then
            echo "Adding ${{github.head_ref}} to active branches"
            jq '.branches += ["${{github.head_ref}}"]' active-branches.json > deploy-pr/pr/active-branches.json
          fi
          if [ ${{github.event.pull_request.state}} = 'closed' ]; then
            echo "Removing ${{github.head_ref}} to active branches"
            jq '.branches -= ["${{github.head_ref}}"]' active-branches.json > deploy-pr/pr/active-branches.json
          fi
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy-pr
          path: deploy-pr/

  deploy:
    runs-on: ubuntu-latest
    needs: update-branches
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download deploy artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: "Github action"
          message: "Update active branches"
          branch: "gh-pages"
