name: Branches

on:
  pull_request:
    types: [opened, reopened]
    branches: ["main"]

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A - Current branch of PR is ${{github.ref}}"
      - run: echo "A - Current branch of PR is ${{github.head_ref}}"
      - run: echo "A - Current branch of PR is ${{github.base_ref}}"
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - run: |
          jq .branches[] active-branches.json  -r
