name: CI on Main

on:
  push:
    branches:
      - "main"

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: echo "Nothing to do"
