name: CI on Main

on:
  push:
    branches:
      - 'main

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: mkdir -p deploy
      - run: cp -a ./active-branches.json ./deploy
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: update-branches
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download deploy artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: "Github action"
          message: "Update active branches"
          branch: "gh-pages"
