name: Version changed

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  check_if_version_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get new version
        id: new_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Get old version
        id: old_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'      
      - name: Compare version
        run: |
          if [[ "${{steps.old_version.outputs.prop}}" == "${{steps.new_version.outputs.prop}}" ]]; then
            echo "Package version has not changed. Version is actually ${{steps.old_version.outputs.prop}}"
            echo "Please upgrade version"
            exit 1
          fi
