name: Version changed

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Target branch ${{ github.event.pull_request.base.ref }}"
      - uses: actions/checkout@v3
        with:
          path: 'new'
      - run: cd new
      - name: Get current package version
        id: new_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'      
      - uses: actions/checkout@v3
        with:
          path: 'old'
          ref: github.event.pull_request.base.ref || main
      - run:  cd ../old
      - name: Get current package version
        id: old_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'      
      - name: Compare version
        run: echo "Old version is ${{steps.new_version.outputs.prop}}, new version is ${{steps.old_version.outputs.prop}}"
