name: Version changed

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Target branch ${{ github.event.pull_request.base.ref }}"
      - uses: actions/checkout@v3
      - name: Get current package version
        id: new_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'      
      - uses: actions/checkout@v3
        with:
          ref: github.event.pull_request.base.ref
      - name: Get current package version
        id: old_version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'      
      - name: Compare version
        run: echo "Old version is ${{steps.new_version.outputs.prop}}, new version is ${{steps.old_version.outputs.prop}}"
