name: Check if version change

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  check_change_version:
    uses: ./.github/workflows/packageVersionchange.yml
    with:
      current_branch: ${{ github.ref }}
      target_branch: ${{ github.event.pull_request.base.ref }}
 
  deploy1:   
    runs-on: ubuntu-latest
    needs:
      - check_change_version
    steps:
      - run: echo "Version has changed ? ${{ needs.check_change_version.outputs.if_version_changed }}"
      - run: echo "Version is ${{ needs.check_change_version.outputs.to_version }}"

  deploy-on-if:   
    runs-on: ubuntu-latest
    needs:
      - check_change_version
    if: ${{ needs.check_change_version.outputs.if_version_changed == 'true' }} 
    steps:
      - run: echo "Version has changed !"
